# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './modules/imageViewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(944, 891)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widgetFields = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetFields.sizePolicy().hasHeightForWidth())
        self.widgetFields.setSizePolicy(sizePolicy)
        self.widgetFields.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widgetFields.setObjectName("widgetFields")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetFields)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widgetFields)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.bTakeFromList = QtWidgets.QPushButton(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTakeFromList.sizePolicy().hasHeightForWidth())
        self.bTakeFromList.setSizePolicy(sizePolicy)
        self.bTakeFromList.setObjectName("bTakeFromList")
        self.horizontalLayout_3.addWidget(self.bTakeFromList)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 16, 0, 1, 1)
        self.tePicture = InputField(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tePicture.sizePolicy().hasHeightForWidth())
        self.tePicture.setSizePolicy(sizePolicy)
        self.tePicture.setMinimumSize(QtCore.QSize(0, 15))
        self.tePicture.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tePicture.setFont(font)
        self.tePicture.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tePicture.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tePicture.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.tePicture.setTabChangesFocus(True)
        self.tePicture.setObjectName("tePicture")
        self.gridLayout_2.addWidget(self.tePicture, 21, 0, 1, 1)
        self.teReading = InputField(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teReading.sizePolicy().hasHeightForWidth())
        self.teReading.setSizePolicy(sizePolicy)
        self.teReading.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teReading.setFont(font)
        self.teReading.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.teReading.setTabChangesFocus(True)
        self.teReading.setObjectName("teReading")
        self.gridLayout_2.addWidget(self.teReading, 8, 0, 1, 1)
        self.teMeaning = InputField(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teMeaning.sizePolicy().hasHeightForWidth())
        self.teMeaning.setSizePolicy(sizePolicy)
        self.teMeaning.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teMeaning.setFont(font)
        self.teMeaning.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.teMeaning.setTabChangesFocus(True)
        self.teMeaning.setObjectName("teMeaning")
        self.gridLayout_2.addWidget(self.teMeaning, 6, 0, 1, 1)
        self.teExampleSentence = InputField(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teExampleSentence.sizePolicy().hasHeightForWidth())
        self.teExampleSentence.setSizePolicy(sizePolicy)
        self.teExampleSentence.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teExampleSentence.setFont(font)
        self.teExampleSentence.setTabChangesFocus(True)
        self.teExampleSentence.setObjectName("teExampleSentence")
        self.gridLayout_2.addWidget(self.teExampleSentence, 11, 0, 1, 1)
        self.teExpression = InputField(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teExpression.sizePolicy().hasHeightForWidth())
        self.teExpression.setSizePolicy(sizePolicy)
        self.teExpression.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        self.teExpression.setFont(font)
        self.teExpression.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.teExpression.setTabChangesFocus(True)
        self.teExpression.setObjectName("teExpression")
        self.gridLayout_2.addWidget(self.teExpression, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widgetFields)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.bExampleSentenceAddReadings = QtWidgets.QPushButton(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bExampleSentenceAddReadings.sizePolicy().hasHeightForWidth())
        self.bExampleSentenceAddReadings.setSizePolicy(sizePolicy)
        self.bExampleSentenceAddReadings.setObjectName("bExampleSentenceAddReadings")
        self.horizontalLayout_2.addWidget(self.bExampleSentenceAddReadings)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widgetFields)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widgetFields)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widgetFields)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.teTranslation = InputField(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teTranslation.sizePolicy().hasHeightForWidth())
        self.teTranslation.setSizePolicy(sizePolicy)
        self.teTranslation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teTranslation.setFont(font)
        self.teTranslation.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.teTranslation.setTabChangesFocus(True)
        self.teTranslation.setObjectName("teTranslation")
        self.gridLayout_2.addWidget(self.teTranslation, 13, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widgetFields)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bExpressionAddReading = QtWidgets.QPushButton(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bExpressionAddReading.sizePolicy().hasHeightForWidth())
        self.bExpressionAddReading.setSizePolicy(sizePolicy)
        self.bExpressionAddReading.setObjectName("bExpressionAddReading")
        self.horizontalLayout.addWidget(self.bExpressionAddReading)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.bAddNote = QtWidgets.QPushButton(self.widgetFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAddNote.sizePolicy().hasHeightForWidth())
        self.bAddNote.setSizePolicy(sizePolicy)
        self.bAddNote.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bAddNote.setAutoDefault(False)
        self.bAddNote.setDefault(False)
        self.bAddNote.setFlat(False)
        self.bAddNote.setObjectName("bAddNote")
        self.gridLayout_2.addWidget(self.bAddNote, 23, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 25, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widgetFields)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 200))
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 455, 559))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.imageScraper = ImageScraper(self.scrollAreaWidgetContents_2)
        self.imageScraper.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.imageScraper.sizePolicy().hasHeightForWidth())
        self.imageScraper.setSizePolicy(sizePolicy)
        self.imageScraper.setMinimumSize(QtCore.QSize(100, 200))
        self.imageScraper.setBaseSize(QtCore.QSize(200, 400))
        self.imageScraper.setObjectName("imageScraper")
        self.gridLayout.addWidget(self.imageScraper, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.bSearchImage = QtWidgets.QPushButton(Form)
        self.bSearchImage.setObjectName("bSearchImage")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bSearchImage)
        self.leCustomQuery = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCustomQuery.sizePolicy().hasHeightForWidth())
        self.leCustomQuery.setSizePolicy(sizePolicy)
        self.leCustomQuery.setClearButtonEnabled(True)
        self.leCustomQuery.setObjectName("leCustomQuery")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leCustomQuery)
        self.checkBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.cbSearchSource = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSearchSource.sizePolicy().hasHeightForWidth())
        self.cbSearchSource.setSizePolicy(sizePolicy)
        self.cbSearchSource.setObjectName("cbSearchSource")
        self.cbSearchSource.addItem("")
        self.cbSearchSource.addItem("")
        self.cbSearchSource.addItem("")
        self.verticalLayout_2.addWidget(self.cbSearchSource)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.cbExampleSearchMethod = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbExampleSearchMethod.sizePolicy().hasHeightForWidth())
        self.cbExampleSearchMethod.setSizePolicy(sizePolicy)
        self.cbExampleSearchMethod.setObjectName("cbExampleSearchMethod")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/alc.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbExampleSearchMethod.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/tatoeba.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbExampleSearchMethod.addItem(icon1, "")
        self.horizontalLayout_4.addWidget(self.cbExampleSearchMethod)
        self.bSearchExampleSentence = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSearchExampleSentence.sizePolicy().hasHeightForWidth())
        self.bSearchExampleSentence.setSizePolicy(sizePolicy)
        self.bSearchExampleSentence.setObjectName("bSearchExampleSentence")
        self.horizontalLayout_4.addWidget(self.bSearchExampleSentence)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.examplesList = ExamplesList(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examplesList.sizePolicy().hasHeightForWidth())
        self.examplesList.setSizePolicy(sizePolicy)
        self.examplesList.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examplesList.setFont(font)
        self.examplesList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.examplesList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.examplesList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.examplesList.setTabKeyNavigation(False)
        self.examplesList.setProperty("showDropIndicator", False)
        self.examplesList.setAlternatingRowColors(True)
        self.examplesList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.examplesList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.examplesList.setObjectName("examplesList")
        self.examplesList.horizontalHeader().setVisible(True)
        self.examplesList.horizontalHeader().setCascadingSectionResizes(True)
        self.examplesList.horizontalHeader().setDefaultSectionSize(400)
        self.examplesList.horizontalHeader().setMinimumSectionSize(200)
        self.examplesList.horizontalHeader().setStretchLastSection(True)
        self.examplesList.verticalHeader().setVisible(False)
        self.examplesList.verticalHeader().setCascadingSectionResizes(True)
        self.examplesList.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.examplesList)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.leInfo = QtWidgets.QLineEdit(Form)
        self.leInfo.setEnabled(True)
        self.leInfo.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.leInfo.setReadOnly(True)
        self.leInfo.setClearButtonEnabled(False)
        self.leInfo.setObjectName("leInfo")
        self.verticalLayout.addWidget(self.leInfo)
        self.actionAdd_Note = QtWidgets.QAction(Form)
        self.actionAdd_Note.setObjectName("actionAdd_Note")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.teExpression, self.teMeaning)
        Form.setTabOrder(self.teMeaning, self.teReading)
        Form.setTabOrder(self.teReading, self.teExampleSentence)
        Form.setTabOrder(self.teExampleSentence, self.teTranslation)
        Form.setTabOrder(self.teTranslation, self.tePicture)
        Form.setTabOrder(self.tePicture, self.bTakeFromList)
        Form.setTabOrder(self.bTakeFromList, self.bExampleSentenceAddReadings)
        Form.setTabOrder(self.bExampleSentenceAddReadings, self.bExpressionAddReading)
        Form.setTabOrder(self.bExpressionAddReading, self.leInfo)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Picture"))
        self.bTakeFromList.setText(_translate("Form", "Take from list"))
        self.label_4.setText(_translate("Form", "Example Sentence"))
        self.bExampleSentenceAddReadings.setText(_translate("Form", "Furigana"))
        self.label_3.setText(_translate("Form", "Reading"))
        self.label_5.setText(_translate("Form", "Translation"))
        self.label_2.setText(_translate("Form", "Meaning"))
        self.label.setText(_translate("Form", "Expression"))
        self.bExpressionAddReading.setText(_translate("Form", "Reading"))
        self.bAddNote.setText(_translate("Form", "Add Note"))
        self.label_10.setText(_translate("Form", "Search Picture"))
        self.bSearchImage.setText(_translate("Form", "Search"))
        self.checkBox.setText(_translate("Form", "Thumbnails (Faster)"))
        self.label_7.setText(_translate("Form", "Search Image by"))
        self.cbSearchSource.setItemText(0, _translate("Form", "Expression"))
        self.cbSearchSource.setItemText(1, _translate("Form", "Meaning"))
        self.cbSearchSource.setItemText(2, _translate("Form", "Custom"))
        self.label_9.setText(_translate("Form", "Example Sentences"))
        self.cbExampleSearchMethod.setItemText(0, _translate("Form", "アルク"))
        self.cbExampleSearchMethod.setItemText(1, _translate("Form", "Tatoeba"))
        self.bSearchExampleSentence.setText(_translate("Form", "Search"))
        self.leInfo.setText(_translate("Form", "HI there"))
        self.actionAdd_Note.setText(_translate("Form", "Add Note"))
        self.actionAdd_Note.setToolTip(_translate("Form", "Add a new Note"))
        self.actionAdd_Note.setShortcut(_translate("Form", "Ctrl+Return"))

from .ExamplesList import ExamplesList
from .ImageScraper import ImageScraper
from .InputField import InputField
